name: Build
on: push

jobs:
  linux_build:
    runs-on: ubuntu-latest
    container: debian:11
    steps:

    - name: Get files
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        apt update -y && apt upgrade -y
        apt install -y make cmake clang lld qemu-system-x86 ovmf

    - name: Build Header
      run: |
        clang ./include/uefi.h -o uefi.pch

    - name: Build with Clang
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_C_COMPILER=clang ../test/
        cmake --build . -- -j 2

    - name: Testing
      run: |
        ctest --parallel 2 --output-on-failure --timeout 60
